LogCollection/LogAnalysis/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from django.conf.urls import url
from LogAnalysis import views

urlpatterns = [
    url(r'^LogAnalysisPage/$', views.LogAnalysisPage, name='LogAnalysisPage'),

    url(r'^TrainingLogByNaiveBayes/$', views.TrainingLogByNaiveBayes, name='TrainingLogByNaiveBayes'),
    url(r'^TrainingLogByMLP/$', views.TrainingLogByMLP, name='TrainingLogByMLP'),
    url(r'^TrainingLogBySVM/$', views.TrainingLogBySVM, name='TrainingLogBySVM'),
    url(r'^TrainingLogByKMeans/$', views.TrainingLogByKMeans, name='TrainingLogByKMeans'),

    url(r'^LogPredictPage/$', views.LogPredictPage, name='LogPredictPage'),
    url(r'^UploadPredictLog/$', views.UploadPredictLog, name='UploadPredictLog'),
    url(r'^PreditLogDelete/$', views.PreditLogDelete, name='PreditLogDelete'),
    url(r'^PredictByMLP/$', views.PredictByMLP, name='PredictByMLP'),
    url(r'^PredictByBayes/$', views.PredictByBayes, name='PredictByBayes'),

    url(r'^BuildingStatisticPage/$', views.BuildingStatisticPage, name='BuildingStatisticPage'),
    url(r'^BuildingStatisticSubmit/$', views.BuildingStatisticSubmit, name='BuildingStatisticSubmit'),

    url(r'^ScoresStatisticPage/$', views.ScoresStatisticPage, name='ScoresStatisticPage'),
    url(r'^ScoresStatisticSubmit/$', views.ScoresStatisticSubmit, name='ScoresStatisticSubmit'),

    url(r'^MLModelsPage/$', views.MLModelsPage, name='MLModelsPage'),
    url(r'^ModelList/$', views.ModelList, name='ModelList'),
    url(r'^AddModelPage/$', views.AddModelPage, name='AddModelPage'),
    url(r'^AddModel/$', views.AddModel, name='AddModel'),
    url(r'^DeleteModel/$', views.DeleteModel, name='DeleteModel'),

    url(r'^DBInit/$', views.DBInit, name='DBInit'),
]

LogCollection/LogCollection/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from webpage import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.views.static import serve
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.homepage),
    url(r'^LogDisplay/', views.LogCollection, name='LogDisplay'),
    url(r'^LogCollection/', include('webpage.urls', namespace='LogCollection')),
    url(r'^LogAnalysisPage/', include('LogAnalysis.urls', namespace='LogAnalysisPage')),
    url(r'^LogPredict/', include('LogPredict.urls', namespace='LogPredict')),
    #config the staticfile path
    url(r'^static/(?P<path>.*)$',serve,{'document_root': settings.STATIC_ROOT}),
]

urlpatterns += staticfiles_urlpatterns()

LogCollection/webpage/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from django.conf.urls import url
from webpage import views

urlpatterns = [
    url(r'^UploadLog/$', views.UploadLog, name='UploadLog'),
    url(r'^get_jenkins_log/$', views.get_jenkins_log, name='get_jenkins_log'),
    url(r'^UploadLogHander/$', views.UploadLogHander, name='UploadLogHander'),
    url(r'^BatchCollectionLog/$', views.BatchCollectionLog, name='BatchCollectionLog'),
    url(r'^get_jenkins_log_by_build_num_internal/$', views.get_jenkins_log_by_build_num_internal,
        name='get_jenkins_log_by_build_num_internal'),
    url(r'^InfoFillInPage/$', views.InfoFillInPage, name='InfoFillInPage'),

    url(r'^CreateErrorType/$', views.CreateErrorType, name='CreateErrorType'),
    url(r'^SaveNewErrorType/$', views.SaveNewErrorType, name='SaveNewErrorType'),

    url(r'^CreateTeam/$', views.CreateTeam, name='CreateTeam'),
    url(r'^SaveNewTeam/$', views.SaveNewTeam, name='SaveNewTeam'),

    url(r'^LogDelete/$', views.LogDelete, name='LogDelete'),
    url(r'^LogsDelete/$', views.LogsDelete, name='LogsDelete'),
    url(r'^LogEditPage/$', views.LogEditPage, name='LogEditPage'),
    url(r'^LogEditSubmit/$', views.LogEditSubmit, name='LogEditSubmit'),

    url(r'^ErrorTypeDelete/$', views.ErrorTypeDelete, name='ErrorTypeDelete'),
    url(r'^ErrorTypeEditPage/$', views.ErrorTypeEditPage, name='ErrorTypeEditPage'),
    url(r'^ErrorTypeEditSubmit/$', views.ErrorTypeEditSubmit, name='ErrorTypeEditSubmit'),

    url(r'^LogTextPage/$', views.LogTextPage, name='LogTextPage'),

    url(r'^LogSelect/$', views.LogSelect, name='LogSelect'),
    url(r'^SelectedLogsUpdateErrorTypes/$', views.SelectedLogsUpdateErrorTypes, name='SelectedLogsUpdateErrorTypes'),
    url(r'^SelectedLogsDelete/$', views.SelectedLogsDelete, name='SelectedLogsDelete'),


    url(r'^SchedulerPage/$', views.SchedulerPage, name='SchedulerPage'),
    url(r'^JobEditPage/$', views.JobEditPage, name='JobEditPage'),
    url(r'^JobEditSubmit/$', views.JobEditSubmit, name='JobEditSubmit'),
    url(r'^Joblist/$', views.Joblist, name='Joblist'),
    url(r'^SaveNewJob/$', views.SaveNewJob, name='SaveNewJob'),
    url(r'^AddNewJobPage/$', views.AddNewJobPage, name='AddNewJobPage'),
    url(r'^JobDelete/$', views.JobDelete, name='JobDelete'),
    url(r'^JobsDelete/$', views.JobsDelete, name='JobsDelete'),
    url(r'^schedulerStart/$', views.schedulerStart, name='schedulerStart'),
    url(r'^schedulerStop/$', views.schedulerStop, name='schedulerStop'),

    url(r'^CleanAll/$', views.CleanAll, name='CleanAll'),
]

LogCollection/LogAnalysis/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib import messages
from django.core.paginator import Paginator
import json
import threading
from AlgorithmModels.NaiveBayesModel import *
from AlgorithmModels.MLPModel import *
from AlgorithmModels.KMeansModel import *
from AlgorithmModels.SVMModel import *
from DataProcessingAndPlot.DataProcessing import *
from DataProcessingAndPlot.DataPlot import timestamp_duration_plot
from DataProcessingAndPlot.DataPlot import scores_statistic_plot
from Untils.TimeUtils import *

# Create your views here.
global plot_job
global plot_model


def DBInit(request):
    try:
        InitMLModel()
    except Exception as e:
        messages.error(request, e)
        return HttpResponse('{"failed":"success"}', content_type='application/json')
    return HttpResponse('{"status":"success"}', content_type='application/json')


def LogAnalysisPage(request):
    context = get_training_jobs()
    return render(request, 'LogAnalysis/LogAnalysisPage.html', context=context)


def TrainingLogByNaiveBayes(request):
    context = get_training_jobs()
    if request.method == "POST":
        training_job = request.POST.get('training_job', "")
        training_path = Job.objects.get(name=training_job).job_dir
        print "training_path:", training_path
        try:
            context.update(training_by_naive_bayes(training_path, job_name=training_job))
        except Exception as e:
            print e
            messages.error(request, e)
        return render(request, 'LogAnalysis/LogAnalysisPage.html', context=context)
    else:
        messages.info(request, "analysis error")
        return render(request, 'LogAnalysis/LogAnalysisPage.html', context=context)


def TrainingLogByMLP(request):
    context = get_training_jobs()
    if request.method == "POST":
        training_job = request.POST.get('training_job', "")
        training_path = Job.objects.get(name=training_job).job_dir
        print "training_path:", training_path
        try:
            context.update(training_by_MLP(training_path, job_name=training_job, feature_d=0))
        except Exception as e:
            print e
            messages.error(request, e)
        return render(request, 'LogAnalysis/LogAnalysisPage.html', context=context)
    else:
        messages.info(request, "analysis error")
        return render(request, 'LogAnalysis/LogAnalysisPage.html', context=context)


def TrainingLogBySVM(request):
    context = get_training_jobs()
    if request.method == "POST":
        training_job = request.POST.get('training_job', "")
        training_path = Job.objects.get(name=training_job).job_dir
        print "training_path:", training_path
        try:
            context.update(training_by_SVM(training_path, job_name=training_job, feature_d=0))
        except Exception as e:
            print e
            messages.error(request, e)
        return render(request, 'LogAnalysis/LogAnalysisPage.html', context=context)
    else:
        messages.info(request, "analysis error")
        return render(request, 'LogAnalysis/LogAnalysisPage.html', context=context)


def TrainingLogByKMeans(request):
    context = get_training_jobs()
    if request.method == "POST":
        training_job = request.POST.get('training_job', "")
        submodel = request.POST.get('submodel', "")
        eps = int(request.POST.get('eps', 2))
        min_samples = int(request.POST.get('min_samples', 2))
        cluster_k = int(request.POST.get('cluster_k', 3))
        feature_d = request.POST.get('feature_d', 'all')
        dbscan = False
        if submodel == 'dbscan':
            dbscan = True
        if feature_d == 'all':
            feature_d = 0
        else:
            feature_d = int(feature_d)

        training_path = Job.objects.get(name=training_job).job_dir
        print "training_path:", training_path
        try:
            context.update(training_by_Kmeans(training_path, job_name=training_job, n_clusters=cluster_k,
                                              feature_d=feature_d, dbscan=dbscan, eps=eps, min_samples=min_samples))
        except Exception as e:
            print e
            messages.error(request, e)
        return render(request, 'LogAnalysis/LogAnalysisPage.html', context=context)
    else:
        messages.info(request, "analysis error")
        return render(request, 'LogAnalysis/LogAnalysisPage.html', context=context)


def LogPredictPage(request):
    if not os.path.isdir(LOG_PREDICT_PATH):
        os.mkdir(LOG_PREDICT_PATH)
    return render(request, 'LogAnalysis/LogPredictPage.html', context=get_context_of_files(LOG_PREDICT_PATH))


def UploadPredictLog(request):
    class MyThread(threading.Thread):
        def __init__(self, threadID, url):
            threading.Thread.__init__(self)
            self.threadID = threadID
            self.url = url

        def run(self):
            # print "Starting thread [%d]" % self.threadID
            print "catching url:", self.url
            build = JobBuild(self.url)
            build.save_console_text(LOG_PREDICT_PATH)

            # print "Exiting thread [%d]" % self.threadID

    if request.method == "POST":
        job_home_url = request.POST.get('job_home_url', None)
        build_num_start = request.POST.get('build_num_start', "")
        build_num_end = request.POST.get('build_num_end', "")
        if build_num_start == "" or build_num_end == "":
            build = JobBuild(job_home_url)
            build.save_console_text(LOG_PREDICT_PATH)
            return render(request, 'LogAnalysis/LogPredictPage.html',
                          context=get_context_of_files(LOG_PREDICT_PATH))

        build_num_vector = [num for num in range(int(build_num_start), int(build_num_end))]
        url_list = [job_home_url+str(build_num)+"/console" for build_num in build_num_vector]

        threads = []
        threadID = 1
        for url in url_list:
            thread = MyThread(threadID, url)
            thread.start()
            threads.append(thread)
            threadID += 1

        for t in threads:
            t.join()
        print "All catching log threads exited!"
        messages.success(request, "哈哈哈哈，上传成功啦!")

    return render(request, 'LogAnalysis/LogPredictPage.html', context=get_context_of_files(LOG_PREDICT_PATH))


def PreditLogDelete(request):
    if request.method == "POST":
        log_name = request.POST.get('predict_log', None)
        os.remove(log_name)
        print "%s has been deleted" % log_name
        messages.success(request, "delete success!")

    return render(request, 'LogAnalysis/LogPredictPage.html', context=get_context_of_files(LOG_PREDICT_PATH))


def PredictByMLP(request):
    context = predict_by_MLP(LOG_PREDICT_PATH)
    return render(request, 'LogAnalysis/LogPredictPage.html', context=context)


def PredictByBayes(request):
    context = predict_by_naive_bayes(LOG_PREDICT_PATH)
    return render(request, 'LogAnalysis/LogPredictPage.html', context=context)


def BuildingStatisticPage(request):
    context = get_training_jobs()
    return render(request, 'LogAnalysis/BuildingStatisticPage.html', context=context)


def BuildingStatisticSubmit(request):
    context = get_training_jobs()
    global plot_job
    time_start = None

    if request.method == "POST":
        plot_job = request.POST.get('training_job', None)
        time_start = get_timestampdelta("OneMonth")

    if request.method == "GET":
        time = request.GET.get("time")
        time_start = get_timestampdelta(time)

    job = Job.objects.get(name=plot_job)
    try:
        fig = timestamp_duration_plot(job, time_start=time_start)
        context['images'] = [fig]
    except Exception as e:
        print "Exception:", e
        messages.error(request, e)
    return render(request, 'LogAnalysis/BuildingStatisticPage.html', context=context)


def ScoresStatisticPage(request):
    context = get_training_jobs()
    models = model_str
    context['models'] = [models]
    return render(request, 'LogAnalysis/ScoresStatisticPage.html', context=context)


def ScoresStatisticSubmit(request):
    context = get_training_jobs()
    models = model_str
    context['models'] = [models]
    global plot_job
    global plot_model
    time_start = None

    if request.method == "POST":
        plot_job = request.POST.get('training_job')
        plot_model = request.POST.get('model')
        time_start = get_timedelta("OneMonth")

    if request.method == "GET":
        time = request.GET.get("time")
        time_start = get_timedelta(time)

    try:
        fig = scores_statistic_plot(plot_job, time_start=time_start, model=plot_model)
        context['images'] = [fig]
    except Exception as e:
        print "Exception:", e
        messages.error(request, e)
    return render(request, 'LogAnalysis/ScoresStatisticPage.html', context=context)


def MLModelsPage(request):
    return render(request, 'LogAnalysis/MLModels.html')


def ModelList(request):
    def tableData(request, dataList):
        if request.method == "POST":
            print(request.POST)
            limit = request.POST.get('limit')  # how many items per page
            offset = request.POST.get('offset')  # how many items in total in the DB

            if dataList:
                response_data = {'total': dataList.count(), 'rows': []}
                if not offset:
                    offset = 0
                if not limit:
                    limit = 10
                page = int(int(offset) / int(limit) + 1)
                pageinator = Paginator(dataList, limit)  # 开始做分页
                data = pageinator.page(page)


LogCollection/templates/LogAnalysis/BuildingStatisticPage.html
{% extends "./../webpage/base.html" %}
{% block content %}
    <h2 class="text-center">Building statistic</h2>
    <div class="search panel panel-default" style="margin-bottom: 0">
        <div class="panel-body form-group" style="margin-bottom:0">
            <form class="form-horizontal" role="form" action="{% url 'LogAnalysisPage:BuildingStatisticSubmit' %}" method="post">
                <div class="form-group">
                    <label for="team" class="col-sm-2 control-label">Job Name</label>
                    <div class="col-sm-9">
                        <select class="form-control" name="training_job">
                            {% for job in training_jobs %}
                                <option id="job_name" value="{{job.name}}">{{job.name}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="form-group" style="margin-bottom:0">
                    <div class="col-sm-offset-2 col-sm-9">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    {% load staticfiles %}

    <div style="overflow: auto; margin:20px" >
        {% for img in images %}
            <img src="{% static img %}">
            <br>
            {% if images is not None %}
                <div style="margin-left: 50px">
                    <a style="background-color: lightcyan" class="btn active" href="{% url 'LogAnalysisPage:BuildingStatisticSubmit' %}?time=OneDay">One day</a>
                    <a style="background-color: lightcyan" class="btn active" href="{% url 'LogAnalysisPage:BuildingStatisticSubmit' %}?time=OneWeek">One week</a>
                    <a style="background-color: lightcyan" class="btn active" href="{% url 'LogAnalysisPage:BuildingStatisticSubmit' %}?time=OneMonth">One month</a>
                    <a style="background-color: lightcyan" class="btn active" href="{% url 'LogAnalysisPage:BuildingStatisticSubmit' %}?time=ThreeMonth">Three month</a>
                    <a style="background-color: lightcyan" class="btn active" href="{% url 'LogAnalysisPage:BuildingStatisticSubmit' %}?time=OneYear">One year</a>
                    <a style="background-color: lightcyan" class="btn active" href="{% url 'LogAnalysisPage:BuildingStatisticSubmit' %}?time=All">All</a>
                </div>
        {% endif %}
        {% endfor %}
    </div>

<br/><br/><br/>
{% endblock %}

LogCollection/templates/LogAnalysis/LogAnalysisPage.html
{% extends "./../webpage/base.html" %}
{% block content %}

    <style>
        input[type=text]{
            height: 33px;
            padding: 12px 20px;
            margin: 8px 0;
            display: inline-block;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }
    </style>
    <p class="text-left"><strong>Select training method</strong></p>
    <button id="btn_NativeBayes" class="btn btn-primary">NativeBayes</button>
    <button id="btn_MLP" class="btn btn-primary">MLP</button>
    <button id="btn_SVM" class="btn btn-primary">SVM</button>
    <button id="btn_Kmeans" class="btn btn-primary">Kmeans</button>
    {% comment %}<p class="text-center"><strong>Log analysis</strong></p>{% endcomment %}
    <br/><br/>

    <form id="NativeBayes" style="display: none" class="form-horizontal" role="form" action="{% url 'LogAnalysisPage:TrainingLogByNaiveBayes' %}" method="post">
        <div class="form-group">
            <label for="team" class="col-sm-offset-2 col-sm-9">[data] Filter error & TFIDF [model] NativeBayes</label>
            <label for="team" class="col-sm-2 control-label">Method NativeBayes</label>
            <div class="col-sm-9">
                <select class="form-control" name="training_job">
                    {% for job in training_jobs %}
                        <option id="dir" value="{{job.name}}">{{job.name}}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-9">
                <button type="submit" class="btn btn-primary">training by Naive Bayes</button>
            </div>
        </div>
    </form>

    <form id="MLP" style="display: none" class="form-horizontal" role="form" action="{% url 'LogAnalysisPage:TrainingLogByMLP' %}" method="post">
        <div class="form-group">
            <label for="team" class="col-sm-offset-2 col-sm-9">[data] Doc2Vec [model] MLP</label>
            <label for="team" class="col-sm-2 control-label">Method MLP</label>
            <div class="col-sm-9">
                <select class="form-control" name="training_job">
                    {% for job in training_jobs %}
                        <option id="dir" value="{{job.name}}">{{job.name}}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-9">
                <button type="submit" class="btn btn-primary">Training by MLP</button>
            </div>
        </div>
    </form>

    <form id="SVM" style="display: none" class="form-horizontal" role="form" action="{% url 'LogAnalysisPage:TrainingLogBySVM' %}" method="post">
        <div class="form-group">
            <label for="team" class="col-sm-offset-2 col-sm-9">[data] Doc2Vec [model] SVM</label>
            <label for="team" class="col-sm-2 control-label">Method SVM</label>
            <div class="col-sm-9">
                <select class="form-control" name="training_job">
                    {% for job in training_jobs %}
                        <option id="dir" value="{{job.name}}">{{job.name}}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-9">
                <button type="submit" class="btn btn-primary">Training by SVM</button>
            </div>
        </div>
    </form>

    <form id="Kmeans" style="display: none" class="form-horizontal" role="form" action="{% url 'LogAnalysisPage:TrainingLogByKMeans' %}" method="post">
        <div class="form-group">
            <label for="team" class="col-sm-offset-2 col-sm-9">[data]  Doc2Vec [model] Kmeans</label>
            <label for="team" class="col-sm-2 control-label">Method Kmeans</label>
            <div class="col-sm-9">
                <select class="form-control" name="training_job">
                    {% for job in training_jobs %}
                        <option id="dir" value="{{job.name}}">{{job.name}}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="team" class="col-sm-2 control-label">Select sub method</label>
            <div class="col-sm-9">
                <select class="form-control" id="submodel" name="submodel">
                    <option value="kmeans">k-means++</option>
                    <option value="dbscan">DBSCAN</option>
                </select>
            </div>
        </div>
        <div class="form-group" id="kmeans">
            <div class="col-sm-offset-2 col-sm-9">
                cluster_k <input type="text" name="cluster_k" placeholder="cluster k" value="3">
                feature_d <input type="text" name="feature_d" placeholder="feature d" value="all">
            </div>
        </div>
        <div class="form-group" style="display: none" id="dbscan">
            <div class="col-sm-offset-2 col-sm-9">
                eps <input type="text" name="eps" placeholder="eps" value="2">
                min_samples <input type="text" name="min_samples" placeholder="min_samples" value="2">
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-9">
                <button type="submit" class="btn btn-primary">Training by Kmean</button>
            </div>
        </div>
    </form>

    {% if images is not None %}
    {% load staticfiles %}
    <div class="text-center">
        <h2 class="text-center">Image display</h2>
        {% for img in images %}
            <img src="{% static img %}">
        {% endfor %}
    </div>
    {% endif %}

    {% if mlp_predicted is not None %}
        <div id="MLP_report">
            <h2 class="text-center">train report</h2>
            <p>MLP</p>
            <pre>{{ mlp_predicted }}</pre>
            <pre>score = {{ mlp_metrics_score }}</pre>
            <pre>{{ mlp_metrics_report }}</pre>
        </div>
    {% endif %}

    {% if svm_predicted is not None %}
        <div id="SVM_report">
            <h2 class="text-center">train report</h2>
            <p>SVM</p>
            <pre>{{ svm_predicted }}</pre>
            <pre>score = {{ svm_metrics_score }}</pre>
            <pre>{{ svm_metrics_report }}</pre>
        </div>
    {% endif %}

    {% if predicted is not None %}
        <div id="NativeBayes_report">
            <h2 class="text-center">train report</h2>
            <p>Naive bayes</p>
            <pre>{{ predicted }}</pre>
            <pre>score = {{ metrics_score }}</pre>
            <pre>{{ metrics_report }}</pre>
        </div>
    {% endif %}

    <div>
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    {% for th in label_th %}
                        <th>
                            <strong>{{ th }}</strong>
                        </th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% for result in km_result %}
                    <tr>
                    <td class="col-sm-2">{{ result.log }}</td>
                    <td class="col-sm-2">{{ result.raw_label }}</td>
                    <td class="col-sm-2">{{ result.km_label }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <br>
    <br>
    <br>

    <script>
        $(document).ready(function(){
            $("#btn_MLP").click(function(){
                $("#MLP").show();
                $("#SVM").hide();
                $("#Kmeans").hide();
                $("#NativeBayes").hide();
                $("#report").show();
                $("#MLP_report").show();
                $("#SVM_report").show();
                $("#NativeBayes_report").hide();
            });
            $("#btn_SVM").click(function(){
                $("#MLP").hide();
                $("#SVM").show();
                $("#Kmeans").hide();
                $("#NativeBayes").hide();
                $("#report").show();
                $("#MLP_report").show();
                $("#SVM_report").show();
                $("#NativeBayes_report").hide();
            });
            $("#btn_Kmeans").click(function(){
                $("#MLP").hide();
                $("#Kmeans").show();
                $("#NativeBayes").hide();
                $("#report").hide();
            });
            $("#btn_NativeBayes").click(function(){
                $("#MLP").hide();
                $("#Kmeans").hide();
                $("#NativeBayes").show();
                $("#report").show();
                $("#MLP_report").hide();
                $("#SVM_report").hide();
                $("#NativeBayes_report").show();
            });

            $("#submodel").change(function(){
                var v = $("#submodel").val();
                if(v == "dbscan") {
                    $("#kmeans").hide();
                    $("#dbscan").show();
                }else{
                     $("#kmeans").show();
                    $("#dbscan").hide();
                }
            });
        });
    </script>

{% endblock %}


LogCollection/templates/LogAnalysis/LogPredictPage.html
{% extends "./../webpage/base.html" %}
{% block content %}
    <p>predict logs</p>
    <div>
        <table border="1">
        <thead>
            <tr>
                <th>Log</th>
                <th>Predict label</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for log in files %}
                <tr>
                    <td class="col-sm-2">{{ log }}</td>
                    <td class="col-sm-2"></td>
                    <td>
                        <form method="post" action="{% url 'LogAnalysisPage:PreditLogDelete' %}">
                            <input type="hidden" name="predict_log" value="{{ log }}">
                            <input type="submit" name="submit" value="delete">
                        </form>
                    </td>
                </tr>
            {% endfor %}

            {% for p in predicted %}
                <tr>
                    <td class="col-sm-2">{{ p.log }}</td>
                    <td class="col-sm-2">{{ p.predict_label }}</td>
                    <td>
                        <form method="post" action="{% url 'LogAnalysisPage:PreditLogDelete' %}">
                            <input type="hidden" name="predict_log" value="{{ p.log }}">
                            <input type="submit" name="submit" value="delete">
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
        </table>
    </div>


    <form action="{% url 'LogAnalysisPage:UploadPredictLog' %}" method="post">
        <p>Jenkins Url</p>
        <input type="text" name="job_home_url"/>
        <p>Build internal</p>
        <input type="text" name="build_num_start" placeholder="build num start"/>
        <input type="text" name="build_num_end" placeholder="build num end"/>
        <input type="submit" name="submit" value="UploadPredictLog"/>
    </form>

    <form action="{% url 'LogAnalysisPage:PredictByMLP' %}" method="post">
        <input type="submit" name="predict" value="PredictByMLP"/>
    </form>

    <form action="{% url 'LogAnalysisPage:PredictByBayes' %}" method="post">
        <input type="submit" name="predict" value="PredictByBayes"/>
    </form>
{% endblock %}