LogCollection/LogAnalysis/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from django.conf.urls import url
from LogAnalysis import views

urlpatterns = [
    url(r'^LogAnalysisPage/$', views.LogAnalysisPage, name='LogAnalysisPage'),

    url(r'^TrainingLogByNaiveBayes/$', views.TrainingLogByNaiveBayes, name='TrainingLogByNaiveBayes'),
    url(r'^TrainingLogByMLP/$', views.TrainingLogByMLP, name='TrainingLogByMLP'),
    url(r'^TrainingLogBySVM/$', views.TrainingLogBySVM, name='TrainingLogBySVM'),
    url(r'^TrainingLogByKMeans/$', views.TrainingLogByKMeans, name='TrainingLogByKMeans'),

    url(r'^LogPredictPage/$', views.LogPredictPage, name='LogPredictPage'),
    url(r'^UploadPredictLog/$', views.UploadPredictLog, name='UploadPredictLog'),
    url(r'^PreditLogDelete/$', views.PreditLogDelete, name='PreditLogDelete'),
    url(r'^PredictByMLP/$', views.PredictByMLP, name='PredictByMLP'),
    url(r'^PredictByBayes/$', views.PredictByBayes, name='PredictByBayes'),

    url(r'^BuildingStatisticPage/$', views.BuildingStatisticPage, name='BuildingStatisticPage'),
    url(r'^BuildingStatisticSubmit/$', views.BuildingStatisticSubmit, name='BuildingStatisticSubmit'),

    url(r'^ScoresStatisticPage/$', views.ScoresStatisticPage, name='ScoresStatisticPage'),
    url(r'^ScoresStatisticSubmit/$', views.ScoresStatisticSubmit, name='ScoresStatisticSubmit'),

    url(r'^MLModelsPage/$', views.MLModelsPage, name='MLModelsPage'),
    url(r'^ModelList/$', views.ModelList, name='ModelList'),
    url(r'^AddModelPage/$', views.AddModelPage, name='AddModelPage'),
    url(r'^AddModel/$', views.AddModel, name='AddModel'),
    url(r'^DeleteModel/$', views.DeleteModel, name='DeleteModel'),

    url(r'^DBInit/$', views.DBInit, name='DBInit'),
]

LogCollection/LogCollection/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from webpage import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.views.static import serve
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.homepage),
    url(r'^LogDisplay/', views.LogCollection, name='LogDisplay'),
    url(r'^LogCollection/', include('webpage.urls', namespace='LogCollection')),
    url(r'^LogAnalysisPage/', include('LogAnalysis.urls', namespace='LogAnalysisPage')),
    url(r'^LogPredict/', include('LogPredict.urls', namespace='LogPredict')),
    #config the staticfile path
    url(r'^static/(?P<path>.*)$',serve,{'document_root': settings.STATIC_ROOT}),
]

urlpatterns += staticfiles_urlpatterns()

LogCollection/LogPredict/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^LogPredictHomePage/$', views.LogPredcitHomePage, name='LogPredcitHomePage'),
    url(r'^PredictDraft/$', views.PredictDraft, name='PredictDraft'),
]

LogCollection/webpage/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from django.conf.urls import url
from webpage import views

urlpatterns = [
    url(r'^UploadLog/$', views.UploadLog, name='UploadLog'),
    url(r'^get_jenkins_log/$', views.get_jenkins_log, name='get_jenkins_log'),
    url(r'^UploadLogHander/$', views.UploadLogHander, name='UploadLogHander'),
    url(r'^BatchCollectionLog/$', views.BatchCollectionLog, name='BatchCollectionLog'),
    url(r'^get_jenkins_log_by_build_num_internal/$', views.get_jenkins_log_by_build_num_internal,
        name='get_jenkins_log_by_build_num_internal'),
    url(r'^InfoFillInPage/$', views.InfoFillInPage, name='InfoFillInPage'),

    url(r'^CreateErrorType/$', views.CreateErrorType, name='CreateErrorType'),
    url(r'^SaveNewErrorType/$', views.SaveNewErrorType, name='SaveNewErrorType'),

    url(r'^CreateTeam/$', views.CreateTeam, name='CreateTeam'),
    url(r'^SaveNewTeam/$', views.SaveNewTeam, name='SaveNewTeam'),

    url(r'^LogDelete/$', views.LogDelete, name='LogDelete'),
    url(r'^LogsDelete/$', views.LogsDelete, name='LogsDelete'),
    url(r'^LogEditPage/$', views.LogEditPage, name='LogEditPage'),
    url(r'^LogEditSubmit/$', views.LogEditSubmit, name='LogEditSubmit'),

    url(r'^ErrorTypeDelete/$', views.ErrorTypeDelete, name='ErrorTypeDelete'),
    url(r'^ErrorTypeEditPage/$', views.ErrorTypeEditPage, name='ErrorTypeEditPage'),
    url(r'^ErrorTypeEditSubmit/$', views.ErrorTypeEditSubmit, name='ErrorTypeEditSubmit'),

    url(r'^LogTextPage/$', views.LogTextPage, name='LogTextPage'),

    url(r'^LogSelect/$', views.LogSelect, name='LogSelect'),
    url(r'^SelectedLogsUpdateErrorTypes/$', views.SelectedLogsUpdateErrorTypes, name='SelectedLogsUpdateErrorTypes'),
    url(r'^SelectedLogsDelete/$', views.SelectedLogsDelete, name='SelectedLogsDelete'),


    url(r'^SchedulerPage/$', views.SchedulerPage, name='SchedulerPage'),
    url(r'^JobEditPage/$', views.JobEditPage, name='JobEditPage'),
    url(r'^JobEditSubmit/$', views.JobEditSubmit, name='JobEditSubmit'),
    url(r'^Joblist/$', views.Joblist, name='Joblist'),
    url(r'^SaveNewJob/$', views.SaveNewJob, name='SaveNewJob'),
    url(r'^AddNewJobPage/$', views.AddNewJobPage, name='AddNewJobPage'),
    url(r'^JobDelete/$', views.JobDelete, name='JobDelete'),
    url(r'^JobsDelete/$', views.JobsDelete, name='JobsDelete'),
    url(r'^schedulerStart/$', views.schedulerStart, name='schedulerStart'),
    url(r'^schedulerStop/$', views.schedulerStop, name='schedulerStop'),

    url(r'^CleanAll/$', views.CleanAll, name='CleanAll'),
]

LogCollection/webpage/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import Http404
from django.shortcuts import render
from django.contrib import messages
from django.core.paginator import Paginator
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
import json
import shutil
import threading
from LogCollection.views import Fsche, Tsche
from models import *
from config import *

# Create your views here.
global filter_logs
for job in Job.objects.all():
    old_path = job.job_dir
    if old_path.split('LogSavingPath')[0] != home_path:
        new_path = os.path.join(home_path, 'LogSavingPath', old_path.split('LogSavingPath')[-1][1:])
        try:
            shutil.move(old_path, new_path)
        except Exception as e:
            print e
        job.job_dir = new_path
        job.save()


def homepage(request):
    context = search_all_logs()
    return render(request, 'webpage/LogDisplay.html', context=context)


def search_all_jobs():
    context = {}
    theader = ['Job Name', 'Job_url', 'Ismonitored', 'FetchSizeOfOneTime', 'TimeSetting', 'Description']
    context['theader'] = theader

    return context


def search_all_error_type():
    context = {}
    ErrorTypes = ErrorType.objects.all()
    context['ErrorTypes'] = ErrorTypes
    theader = ['Error Name', 'Description', 'Create at']
    context['theader'] = theader
    return context


def search_all_teams():
    context = {}
    Teams = Team.objects.all()
    context['Teams'] = Teams
    theader = ['Team Name', 'Description', 'Create at']
    context['theader'] = theader
    return context


def search_all_logs():
    context = {}
    logs = Log.objects.all()
    context['logs'] = logs
    context['logs_number'] = len(logs)

    global filter_logs
    filter_logs = logs
    context.update(get_all_select())

    return context


def get_all_select():
    context = {}
    theader = ['Log Name', 'Team', 'ErrorType', 'Exit Status', 'Codes Number', 'Is training set', 'Duration', 'Timestamp', 'Description']
    context['theader'] = theader
    context['Teams'] = Team.objects.all()
    context['ErrorTypes'] = ErrorType.objects.all()
    status = ExitStatus.objects.all()
    for statu in status:
        if not Log.objects.filter(exit_status=statu):
            statu.delete()
    context['Status'] = ExitStatus.objects.all()
    return context


def CleanAll(request):
    for team in Team.objects.all():
        team.delete()
    Team.objects.create(name="Undefine Team", description="Undefine the team")
    Team.objects.create(name="UPG", description="")
    Team.objects.create(name="HSS", description="")

    for log in Log.objects.all():
        log.delete()

    for error in ErrorType.objects.all():
        error.delete()

    ErrorType.objects.create(name="SUCCESS", description="")
    ErrorType.objects.create(name="ABORTED", description="")
    ErrorType.objects.create(name="Undefine Error", description="Undefine the error type")
    ErrorType.objects.create(name="GicCloneError", description="Git clone error")
    ErrorType.objects.create(name="DenpendenciesError", description="Could not resolve dependencies")

    for stat in ExitStatus.objects.all():
        stat.delete()

    try:
        shutil.rmtree(LOG_SAVING_PATH)
        msg = "%s has been deleted" % LOG_SAVING_PATH
    except:
        msg = "something wrong for delete %s" % LOG_SAVING_PATH

    messages.success(request, msg)

    context = search_all_logs()
    return render(request, 'webpage/LogDisplay.html', context=context)


def LogCollection(request):
    context = search_all_logs()
    return render(request, 'webpage/LogDisplay.html', context=context)


def InfoFillInPage(request):
    context = search_all_error_type()
    context.update(search_all_teams())
    return render(request, 'webpage/InfoFillInPage.html', context=context)


def BatchCollectionLog(request):
    context = search_all_error_type()
    context.update(search_all_teams())
    return render(request, 'webpage/BatchCollectionLog.html', context=context)


def UploadLog(request):
    context = search_all_error_type()
    context.update(search_all_teams())
    return render(request, 'webpage/UploadLog.html', context=context)


def CreateErrorType(request):
    context = search_all_error_type()
    return render(request, 'webpage/CreateErrorType.html', context=context)


def SaveNewErrorType(request):
    context = search_all_error_type()
    if request.method == "POST":
        new_error_type = request.POST.get('new_error_type', None)
        description = request.POST.get('description', "")

        if ErrorType.objects.filter(name=new_error_type):
            messages.success(request, "the error type is exist")
            return render(request, 'webpage/CreateErrorType.html', context=context)

        ErrorType.objects.create(name=new_error_type, description=description).save()
        messages.success(request, "create new error type success!")

    return render(request, 'webpage/CreateErrorType.html', context=search_all_error_type())


def CreateTeam(request):
    context = search_all_teams()
    return render(request, 'webpage/CreateTeam.html', context=context)


def SaveNewTeam(request):
    context = search_all_teams()

    if request.method == "POST":
        new_team = request.POST.get('new_team', None)
        description = request.POST.get('description', "")

        if Team.objects.filter(name=new_team):
            messages.success(request, "the team is exist")
            return render(request, 'webpage/CreateTeam.html', context=context)

        Team.objects.create(name=new_team, description=description).save()
        messages.success(request, "create new team success!")

    return render(request, 'webpage/CreateTeam.html', context=search_all_teams())


def UploadLogHander(request):
    context = search_all_error_type()
    context.update(search_all_teams())
    if not Job.objects.filter(name="Upload job"):
        Job.objects.create(name="Upload job", ismonitored=False)
    if not ExitStatus.objects.filter(name='Unknown'):
        ExitStatus.objects.create(name='Unknown')

    if request.method == "POST":
        log_file = request.FILES.getlist('logfile', [])
        team = request.POST.get('team', None)
        description = request.POST.get('description', "")
        error_type = request.POST.get('error_type', None)
        save_path = os.path.join(LOG_SAVING_PATH, "Upload job")

        for file in log_file:
            if Log.objects.filter(name=file.name):
                msg = "the log file[%s] has been exist" % file.name
                print msg
                messages.error(request, msg)
                continue

            if not os.path.exists(save_path):
                os.makedirs(save_path)

            log_name = os.path.join(save_path, file.name)
            with open(log_name, 'wb+') as fw:
                # 根据上传的流中的数据一点一点往内存中写
                for c in file.chunks():
                    fw.write(c)
                codes_num = len(fw.read())

            log = Log.objects.create(name=os.path.basename(log_name),
                                     job=Job.objects.get(name="Upload job"),
                                     codes_number=codes_num,
                                     istrainingset=False,
                                     description=description)
            log.save()

        messages.success(request, "哈哈哈哈，上传成功啦!")
        return render(request, 'webpage/UploadLog.html', context=context)
    else:
        messages.error(request, "ERROR")
        return render(request, 'webpage/UploadLog.html', context=context)


def get_jenkins_log(request):
    if request.method == "POST":
        url = request.POST.get('log_url', None)
        team = request.POST.get('team', None)
        error_type = request.POST.get('error_type', "")
        description = request.POST.get('description', "")
        build = JobBuild(url)
        if not build.save(scheduler=False, team_name=team, error_type=error_type, description=description):
            messages.success(request, "哈哈哈哈，上传成功啦!")
        else:
            messages.error(request, "哦哟， 失败了呀！")

    context = search_all_logs()
    return render(request, 'webpage/LogDisplay.html', context=context)


def get_jenkins_log_by_build_num_internal(request):
    class MyThread(threading.Thread):
        def __init__(self, threadID, url):
            threading.Thread.__init__(self)
            self.threadID = threadID
            self.url = url

        def run(self):
            threadLock = threading.Lock()
            # print "Starting thread [%d]" % self.threadID
            print "fetching log:", self.url
            build = JobBuild(self.url)
            threadLock.acquire()
            build.save(scheduler=True)
            threadLock.release()
            # print "Exiting thread [%d]" % self.threadID

    if request.method == "POST":
        job_home_url = request.POST.get('job_home_url', None)
        description = request.POST.get('description', "")
        build_num_start = request.POST.get('build_num_start', 0)
        build_num_end = request.POST.get('build_num_end', 1)
        build_num_vector = [num for num in range(int(build_num_start), int(build_num_end))]
        url_list = [job_home_url+str(build_num) + '/' for build_num in build_num_vector]

        threads = []
        threadID = 1
        for url in url_list:
            thread = MyThread(threadID, url)
            thread.start()
            threads.append(thread)
            threadID += 1

        for t in threads:
            t.join()
        print "All catching log threads exited!"

LogCollection/templates/webpage/CreateTeam.html
{% extends "./base.html" %}
{% block content %}

    <p class="text-center"><strong>Exist team display</strong></p>
    <div>
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    {% for th in theader %}
                        <th>
                            <strong>{{ th }}</strong>
                        </th>
                    {% endfor %}
                </tr>
            </thead>
        <tbody>
            {% for team in Teams %}
                <tr>
                    <td class="col-sm-2">{{ team.name }}</td>
                    <td class="col-sm-2">{{ team.description }}</td>
                    <td class="col-sm-2">{{ team.create_at }}</td>
                </tr>
            {% endfor %}
        </tbody>
        </table>
    </div>

    <br/>
    <p class="text-center"><strong>Create new team</strong></p>
    <br/>
    <form class="form-horizontal" role="form" action="{% url 'LogCollection:SaveNewTeam' %}" method="post">
        <div class="form-group">
            <label for="new_team" class="col-sm-2 control-label">Team</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" id="new_team" name="new_team" placeholder="Please input description">
            </div>
        </div>
        <div class="form-group">
            <label for="description" class="col-sm-2 control-label">Description</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" id="description" name="description" placeholder="Please input description">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-9">
                <button type="submit" class="btn btn-default">Submit</button>
            </div>
        </div>
    </form>
    <br/>

    {% if messages %}
        <script>
            {% for msg in messages %}
                alert('{{ msg.message }}');
            {% endfor %}
        </script>
    {% endif %}
{% endblock %}

LogCollection/templates/webpage/LogTextPage.html
{% extends "./base.html" %}
{% block content %}

    <p class="text-center"><strong>Show log details</strong></p>

    {% autoescape off%}
        <div>
            {% for line in log_txt %}
                {{ line }}<br>
            {% endfor %}
        </div><br/><br/><br/><br/>
    {% endautoescape %}

    {% if messages %}
        <script>
            {% for msg in messages %}
                alert('{{ msg.message }}');
            {% endfor %}
        </script>
    {% endif %}

{% endblock %}

LogCollection/templates/webpage/base.html
<!DOCTYPE html>
<!-- saved from url=(0045) -->
<html>
<head>
    {% load staticfiles %}
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AIDevOps</title>
{#    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">#}
{#    <script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>#}
{#    <link href="http://{{ request.get_host }}{% static '/js/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">#}
{#    <script src="http://{{ request.get_host }}{% static '/js/bootstrap-3.3.7-dist/js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>#}
{#    #}
{#    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>#}


    <link href="http://{{ request.get_host }}{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="http://{{ request.get_host }}{% static 'css/plugins/bootstrap-table/bootstrap-table.min.css' %}" rel="stylesheet">
    <link href="http://{{ request.get_host }}{% static 'css/animate.min.css' %}" rel="stylesheet" type="text/css">
    <link rel="http://{{ request.get_host }}{% static 'css/plugins/bootstrapValidator/bootstrapValidator.min.css' %}"/>

    <script src="http://{{ request.get_host }}{% static 'js/jquery.min.js' %}"></script>
    <script src="http://{{ request.get_host }}{% static 'js/bootstrap.min.js' %}"></script>
    <script src="http://{{ request.get_host }}{% static 'js/plugins/bootstrap-table/bootstrap-table.min.js' %}"></script>
    <script src="http://{{ request.get_host }}{% static 'js/plugins/bootstrap-table/bootstrap-table-zh-CN.min.js' %}"></script>
    <script src="http://{{ request.get_host }}{% static 'js/plugins/bootstrapValidator/bootstrapValidator.min.js' %}"></script>

    <link href="http://{{ request.get_host }}{% static 'css/frame.css' %}" rel="stylesheet" type="text/css">
    <link href="http://{{ request.get_host }}{% static 'css/index.css' %}" rel="stylesheet" type="text/css">
    <link href="http://{{ request.get_host }}{% static 'css/menu.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
<div class="navbar">
    <div class="navbar-header">
        <div class="navbar-brand">AIDevOps</div>
        <div class="navbar-brand navbar-brand-compact">AI</div>
    </div>
    <ul class="nav navbar-nav">
        <li><a id="toggle"><span class="glyphicon glyphicon-align-justify"></span></a></li>
        <li><a href="#"><i class="glyphicon glyphicon-film"></i><span>Demo</span></a></li>
        <li><a href="#"><i class="glyphicon glyphicon-list-alt"></i><span>Docs</span></a></li>
        <li><a href="#"><i class="glyphicon glyphicon-certificate"></i><span>Team</span></a></li>
        <li class="dropdown">
            <a type="button" class="dropdown-toggle" data-toggle="dropdown">
                <i class="glyphicon glyphicon-cog"></i><span>SystemConfig</span><b class="caret"></b>
            </a>
            <ul class="dropdown-menu pull-right" style="min-width: 100%">
                <li><a id="dbinit" href="#"><i class="glyphicon glyphicon-globe"></i>DBInit</a></li>
{#                <li><a href="#"><i class="glyphicon glyphicon-star"></i> LoginInfo</a></li>#}
{#                <li><a href="#"><i class="glyphicon glyphicon-star-empty"></i> Exit</a></li>#}
            </ul>
        </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><i class="glyphicon glyphicon-record"></i>ToDo</a></li>
        <li><a href="#"><i class="glyphicon glyphicon-tags"></i>ChangePwd</a></li>
        <li class="dropdown">
            <a type="button" class="dropdown-toggle" data-toggle="dropdown">
                <i class="glyphicon glyphicon-user"></i><span>UserInfo</span><b class="caret"></b>
            </a>
            <ul class="dropdown-menu pull-right" style="min-width: 100%">
                <li><a href="#"><i class="glyphicon glyphicon-star"></i> LoginInfo</a></li>
                <li><a href="#"><i class="glyphicon glyphicon-star-empty"></i> Exit</a></li>
            </ul>
        </li>
    </ul>
</div>

<div class="container">
    <div class="sidebar">
        <div id="mCSB_1" class="mCustomScrollBox" style="max-height: none;" tabindex="0">
            <div class="sidebar-toggle"><i class="glyphicon glyphicon-th-list"></i></div>
            <div id="mainMenu">
                <ul class="menu">
                    <li class=""><a class="menu-title" data-id="a" href="{% url 'LogDisplay' %}"><i class="glyphicon glyphicon-home"></i><span class="menu-text">Display LOG</span></a>
                    <li class="has-children"><a class="menu-title" data-id="1"><i class="glyphicon glyphicon-cloud-download"></i><span class="menu-text">UPLOAD LOG</span><span class="glyphicon glyphicon-chevron-down"></span></a>
                        <ul class="menu-submenu">
                            <li class="bu" role="presentation"><a class="menu-title" role="menuitem" data-id="u" href="{% url 'LogCollection:InfoFillInPage' %}"><i class="glyphicon glyphicon-leaf"></i><span class="menu-text">By URL</span></a></li>
                            <li class="bd" role="presentation"><a class="menu-title" role="menuitem" data-id="d" href="{% url 'LogCollection:UploadLog' %}"><i class="glyphicon glyphicon-leaf"></i><span class="menu-text">By Directory</span></a></li>
                            <li class="bb" role="presentation"><a class="menu-title" role="menuitem" data-id="b" href="{% url 'LogCollection:BatchCollectionLog' %}"><i class="glyphicon glyphicon-leaf"></i><span class="menu-text">By Batch</span></a></li>
                        </ul>
                    </li>
                    <li class="has-children-1"><a class="menu-title" data-id="1"><i class="glyphicon glyphicon-eye-open"></i><span class="menu-text">ANALYSIS LOG</span><span class="glyphicon glyphicon-chevron-down"></span></a>
                        <ul class="menu-submenu-1">
                            <li class="bu" role="presentation"><a class="menu-title" role="menuitem" data-id="u" href="{% url 'LogAnalysisPage:LogAnalysisPage' %}"><i class="glyphicon glyphicon-leaf"></i><span class="menu-text">Training log</span></a></li>
                            <li class="bd" role="presentation"><a class="menu-title" role="menuitem" data-id="d" href="{% url 'LogAnalysisPage:MLModelsPage' %}"><i class="glyphicon glyphicon-leaf"></i><span class="menu-text">ML models</span></a></li>
                        </ul>
                    </li>
                    <li class=""><a class="menu-title" data-id="ctype" href="{% url 'LogCollection:CreateErrorType' %}"><i class="glyphicon glyphicon-tree-conifer"></i><span class="menu-text">Create new error type</span></a></li>
                    <li class=""><a class="menu-title" data-id="cteam" href="{% url 'LogCollection:CreateTeam' %}"><i class="glyphicon glyphicon-plus-sign"></i><span class="menu-text">Create new team</span></a></li>
                    <li class=""><a class="menu-title" data-id="plot" href="{% url 'LogAnalysisPage:BuildingStatisticPage' %}"><i class="glyphicon glyphicon-tree-deciduous"></i><span class="menu-text">Plot</span></a></li>
                    <li class=""><a class="menu-title" data-id="schedule" href="{% url 'LogCollection:SchedulerPage' %}"><i class="glyphicon glyphicon-asterisk"></i><span class="menu-text">Schedule Task</span></a></li>
                    <li class=""><a class="menu-title" data-id="schore" href="{% url 'LogAnalysisPage:ScoresStatisticPage' %}"><i class="glyphicon glyphicon-tint"></i><span class="menu-text">Scores Statistic</span></a></li>
                    <li class=""><a class="menu-title" data-id="predict" href="{% url 'LogPredict:LogPredcitHomePage' %}"><i class="glyphicon glyphicon-tint"></i><span class="menu-text">Log Predict</span></a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="main">
        <div class="mainContent">
            {% block content %}Empty page{% endblock %}
        </div>
<!--<iframe name="main" id="Main" frameborder="no" scrolling="auto" width="100%" height="100%" height="auto" allowtransparency="true" src="{% url 'LogCollection:InfoFillInPage' %}"></iframe>
-->
    </div>
</div>

<div class="footer">
Copyright AIDevOps
</div>
    {% if messages %}
        <script>
            {% for msg in messages %}
                alert('{{ msg.message }}');
            {% endfor %}
        </script>
    {% endif %}
</body>
</html>

<script>
    $(".has-children-1").click(function(){
        $(".menu-submenu-1").toggle();
    });
    $(".has-children").click(function(){
        $(".menu-submenu").toggle();
    });
    $("button").addClass("btn btn-primary");

    //停止scheduler事件按钮
    $('#dbinit').click(function(){
        if(confirm('Are you sure to init database?')){
            $.ajax({
                type:'post',
                traditional :true,
                url:'{% url 'LogAnalysisPage:DBInit' %}',
                dataType: 'json',
                success:function(data){
                    if(data.status == 'success'){
                        alert("Scheduler start success");
                    }else {
                        alert("Scheduler start failed");
                    }
                }
            });
        }
        return false;
    });

    {% block script %}{% endblock %}
</script>